In [3]:
import numpy as np

In [4]:
array6409 = np.loadtxt("NACA6409.dat", skiprows=1)
array2412 = np.loadtxt("NACA2412.dat", skiprows=1)

In [22]:
x = array6409[:,0]

In [56]:
np.where(x == 0)[0][0]

49

In [57]:
list(x).index(0)

49

In [37]:
x[:50]

array([1.0000e+00, 9.9280e-01, 9.7989e-01, 9.6352e-01, 9.4455e-01,
       9.2350e-01, 9.0075e-01, 8.7658e-01, 8.5123e-01, 8.2489e-01,
       7.9774e-01, 7.6991e-01, 7.4154e-01, 7.1275e-01, 6.8365e-01,
       6.5434e-01, 6.2492e-01, 5.9547e-01, 5.6607e-01, 5.3680e-01,
       5.0774e-01, 4.7895e-01, 4.5050e-01, 4.2246e-01, 3.9488e-01,
       3.6782e-01, 3.4135e-01, 3.1551e-01, 2.9035e-01, 2.6594e-01,
       2.4231e-01, 2.1951e-01, 1.9760e-01, 1.7661e-01, 1.5660e-01,
       1.3760e-01, 1.1965e-01, 1.0280e-01, 8.7090e-02, 7.2560e-02,
       5.9240e-02, 4.7170e-02, 3.6390e-02, 2.6940e-02, 1.8850e-02,
       1.2150e-02, 6.8800e-03, 3.0800e-03, 7.8000e-04, 0.0000e+00])

In [39]:
x[49:]

array([0.0000e+00, 7.8000e-04, 3.0800e-03, 6.8800e-03, 1.2150e-02,
       1.8850e-02, 2.6940e-02, 3.6390e-02, 4.7170e-02, 5.9240e-02,
       7.2560e-02, 8.7090e-02, 1.0280e-01, 1.1965e-01, 1.3760e-01,
       1.5660e-01, 1.7661e-01, 1.9760e-01, 2.1951e-01, 2.4231e-01,
       2.6594e-01, 2.9035e-01, 3.1551e-01, 3.4135e-01, 3.6782e-01,
       3.9488e-01, 4.2246e-01, 4.5050e-01, 4.7895e-01, 5.0774e-01,
       5.3680e-01, 5.6607e-01, 5.9547e-01, 6.2492e-01, 6.5434e-01,
       6.8365e-01, 7.1275e-01, 7.4154e-01, 7.6991e-01, 7.9774e-01,
       8.2489e-01, 8.5123e-01, 8.7658e-01, 9.0075e-01, 9.2350e-01,
       9.4455e-01, 9.6352e-01, 9.7989e-01, 9.9280e-01, 1.0000e+00])

In [60]:
def split_airfoil(np_arr):
    x_cord = np_arr[:,0]
    ref_idx = list(x_cord).index(0)
    # find the index that x_cord == 0
    upper = np_arr[:ref_idx+1]
    lower = np_arr[ref_idx:]
    return upper, lower

In [123]:
split_airfoil(array6409)[1]

array([[ 0.0000e+00,  0.0000e+00],
       [ 7.8000e-04, -3.4400e-03],
       [ 3.0800e-03, -6.3200e-03],
       [ 6.8800e-03, -8.6400e-03],
       [ 1.2150e-02, -1.0430e-02],
       [ 1.8850e-02, -1.1700e-02],
       [ 2.6940e-02, -1.2480e-02],
       [ 3.6390e-02, -1.2800e-02],
       [ 4.7170e-02, -1.2690e-02],
       [ 5.9240e-02, -1.2170e-02],
       [ 7.2560e-02, -1.1300e-02],
       [ 8.7090e-02, -1.0090e-02],
       [ 1.0280e-01, -8.5900e-03],
       [ 1.1965e-01, -6.8500e-03],
       [ 1.3760e-01, -4.9000e-03],
       [ 1.5660e-01, -2.7900e-03],
       [ 1.7661e-01, -5.7000e-04],
       [ 1.9760e-01,  1.7100e-03],
       [ 2.1951e-01,  4.0100e-03],
       [ 2.4231e-01,  6.2700e-03],
       [ 2.6594e-01,  8.4500e-03],
       [ 2.9035e-01,  1.0490e-02],
       [ 3.1551e-01,  1.2350e-02],
       [ 3.4135e-01,  1.3970e-02],
       [ 3.6782e-01,  1.5310e-02],
       [ 3.9488e-01,  1.6330e-02],
       [ 4.2246e-01,  1.7080e-02],
       [ 4.5050e-01,  1.7740e-02],
       [ 4.7895e-01,

In [119]:
enum = list(enumerate(array6409[:50]))
small_sum = 0
large_sum = 0
for index, value in enum[:-1]:
    small_sum += (value[0] - enum[index+1][1][0])*value[1]
    large_sum += (value[0] - enum[index+1][1][0])*enum[index+1][1][1] 
print(small_sum, large_sum)
print(0.5*(small_sum + large_sum))

0.07020977420000002 0.0713724131
0.07079109365000001


In [120]:
enum = list(enumerate(array6409[49:]))
small_sum = 0
large_sum = 0
for index, value in enum[:-1]:
    small_sum += (value[0] - enum[index+1][1][0])*value[1]
    large_sum += (value[0] - enum[index+1][1][0])*enum[index+1][1][1] 
print(small_sum, large_sum)
print(0.5*(small_sum + large_sum))

-0.0090747592 -0.009253981499999996
-0.009164370349999998


In [121]:
def get_area(arr):
    enum = list(enumerate(arr))
    small_sum = 0
    large_sum = 0
    for index, value in enum[:-1]:
        small_sum += (value[0] - enum[index+1][1][0])*value[1]
        large_sum += (value[0] - enum[index+1][1][0])*enum[index+1][1][1] 
    return 0.5*(small_sum + large_sum)

In [124]:
def cross_section(np_arr):
    splited = split_airfoil(np_arr)
    area = 0
    for item in splited:
        area += get_area(item)
    return area

In [125]:
cross_section(array6409)

0.06162672330000001

In [126]:
cross_section(array2412)

0.082167074

In [5]:
import pandas as pd
df = pd.DataFrame(array6409)
df.to_excel("test.xlsx")