In [2]:
from xfoil import XFoil

In [53]:
xf = XFoil()

In [4]:
from xfoil.test import *

In [42]:
import numpy as np

In [36]:
array = np.loadtxt("NACA6409.dat", skiprows=1)

In [60]:
from xfoil.model import Airfoil

In [54]:
naca6409 = Airfoil(x=array[:,0], y=array[:,1])

In [71]:
xf = XFoil()
xf.airfoil = naca6409
xf.Re = 82000.0
xf.max_iter = 400
xf.a(17)

(1.1482601165771484,
 0.22458294034004211,
 -0.13075758516788483,
 -2.29042649269104)

In [34]:
a, cl, cd, cm, cp = xf.aseq(0,15,0.5)

In [35]:
xf.aseq(0,15,0.5)

(array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
         5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
        11. , 11.5, 12. , 12.5,  nan,  nan, 14. , 14.5]),
 array([-0.06431956,  0.02774251,  0.12939762,  0.20639464,  0.29713708,
         0.35657737,  0.42086142,  0.49094483,  0.56699753,  0.64396244,
         0.6938144 ,  0.74485147,  0.83038008,  0.88067764,  0.94144017,
         0.99716395,  1.03346753,  1.06016743,  1.09244072,  1.1243149 ,
         1.14605629,  1.16958189,  1.1451304 ,  1.09181178,  1.01590264,
         0.95413482,         nan,         nan,  0.75483686,  0.80321556]),
 array([0.02449794, 0.02666222, 0.02875526, 0.03034821, 0.03184428,
        0.03330315, 0.03464805, 0.03572888, 0.03629893, 0.03619942,
        0.03711412, 0.03765804, 0.03528424, 0.03509488, 0.03376903,
        0.03273857, 0.03327281, 0.03559441, 0.03874994, 0.0436809 ,
        0.04839321, 0.05483542, 0.0628339 , 0.07196066, 0.08563953,
        0.1038

In [31]:
cl, cd, cm, cp = xf.a(10)

In [32]:
xf.a(13)

(nan, nan, nan, nan)

In [33]:
cl

nan