In [1]:
from xfoil import XFoil

In [2]:
xf = XFoil()

In [3]:
from xfoil.test import *

In [4]:
import numpy as np

In [5]:
array = np.loadtxt("NACA6409.dat", skiprows=1)

In [6]:
from xfoil.model import Airfoil

In [7]:
naca6409 = Airfoil(x=1.155*array[:,0], y=2.541*array[:,1])

In [16]:
xf = XFoil()
xf.airfoil = naca6409
xf.Re = 66948
xf.max_iter = 200
xf.n_crit = 9.00
xf.xtr = [1.00, 1.00]
xf.M = 0
xf.a(17.8)

(1.3608604669570923,
 0.3009273409843445,
 -0.3354739844799042,
 -1.2110896110534668)

In [17]:
xf = XFoil()
xf.airfoil = naca6409
xf.Re = 48009
xf.max_iter = 1000
xf.n_crit = 9.00
xf.xtr = [1.00, 1.00]
xf.M = 0
xf.a(12.5)

(3.5347068309783936,
 0.04835117235779762,
 -0.8190194964408875,
 -3.607102394104004)

In [18]:
a, cl, cd, cm, cp = xf.aseq(0,15,0.5)

In [19]:
import matplotlib.pyplot as plt
plt.plot(a, cl)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [22]:
xf.aseq(0,15,0.5)

(array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
         5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
        11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5]),
 array([0.62724257, 0.67468327, 0.73153228, 0.80403018, 0.85194558,
        0.9075433 , 0.96697521, 1.0118978 , 1.07479966, 1.11285329,
        1.17598593, 1.2083739 , 1.27210844, 1.29934549, 1.36804318,
        1.42103171, 1.467013  , 1.4979248 , 1.50018668, 1.44608128,
        1.39877915, 1.37379444, 1.36292076, 1.37793851, 1.42740619,
        1.48730564, 1.4989382 , 1.49098885, 1.46788907, 1.43643117]),
 array([0.02187271, 0.02064855, 0.02089737, 0.0202619 , 0.02094622,
        0.02143299, 0.0215523 , 0.02279576, 0.02288097, 0.02461034,
        0.02480107, 0.02694546, 0.02715545, 0.02959299, 0.02959117,
        0.02840242, 0.02606277, 0.02554992, 0.0258131 , 0.03052559,
        0.0380793 , 0.04487331, 0.05084274, 0.0547463 , 0.05773814,
        0.06313134, 0.06978228, 0.07776281, 

In [28]:
cl, cd, cm, cp = xf.a(13)
cp

-5.401570796966553

In [24]:
xf.a(13)

(1.498945713043213,
 0.06978219002485275,
 -0.06951639801263809,
 -5.401588439941406)

In [25]:
cl

1.3987791538238525

In [26]:
import math
a = math.sin(math.radians(30))

In [27]:
a

0.49999999999999994