In [2]:
from xfoil import XFoil

In [3]:
xf = XFoil()

In [4]:
from xfoil.test import *

In [42]:
import numpy as np

In [54]:
array = np.loadtxt("NACA2412.dat", skiprows=1)

In [55]:
array

array([[ 1.0000e+00,  1.2600e-03],
       [ 9.9280e-01,  2.7400e-03],
       [ 9.7989e-01,  5.3700e-03],
       [ 9.6352e-01,  8.6200e-03],
       [ 9.4455e-01,  1.2310e-02],
       [ 9.2350e-01,  1.6290e-02],
       [ 9.0075e-01,  2.0450e-02],
       [ 8.7658e-01,  2.4740e-02],
       [ 8.5123e-01,  2.9070e-02],
       [ 8.2489e-01,  3.3400e-02],
       [ 7.9774e-01,  3.7690e-02],
       [ 7.6991e-01,  4.1900e-02],
       [ 7.4154e-01,  4.6000e-02],
       [ 7.1275e-01,  4.9950e-02],
       [ 6.8365e-01,  5.3740e-02],
       [ 6.5434e-01,  5.7340e-02],
       [ 6.2492e-01,  6.0730e-02],
       [ 5.9547e-01,  6.3880e-02],
       [ 5.6607e-01,  6.6790e-02],
       [ 5.3680e-01,  6.9440e-02],
       [ 5.0774e-01,  7.1800e-02],
       [ 4.7895e-01,  7.3870e-02],
       [ 4.5050e-01,  7.5640e-02],
       [ 4.2246e-01,  7.7090e-02],
       [ 3.9488e-01,  7.8210e-02],
       [ 3.6782e-01,  7.8930e-02],
       [ 3.4135e-01,  7.9220e-02],
       [ 3.1551e-01,  7.9070e-02],
       [ 2.9035e-01,

In [56]:
x = array[:,0]

In [57]:
x

array([1.0000e+00, 9.9280e-01, 9.7989e-01, 9.6352e-01, 9.4455e-01,
       9.2350e-01, 9.0075e-01, 8.7658e-01, 8.5123e-01, 8.2489e-01,
       7.9774e-01, 7.6991e-01, 7.4154e-01, 7.1275e-01, 6.8365e-01,
       6.5434e-01, 6.2492e-01, 5.9547e-01, 5.6607e-01, 5.3680e-01,
       5.0774e-01, 4.7895e-01, 4.5050e-01, 4.2246e-01, 3.9488e-01,
       3.6782e-01, 3.4135e-01, 3.1551e-01, 2.9035e-01, 2.6594e-01,
       2.4231e-01, 2.1951e-01, 1.9760e-01, 1.7661e-01, 1.5660e-01,
       1.3760e-01, 1.1965e-01, 1.0280e-01, 8.7090e-02, 7.2560e-02,
       5.9240e-02, 4.7170e-02, 3.6390e-02, 2.6940e-02, 1.8850e-02,
       1.2150e-02, 6.8800e-03, 3.0800e-03, 7.8000e-04, 0.0000e+00,
       7.8000e-04, 3.0800e-03, 6.8800e-03, 1.2150e-02, 1.8850e-02,
       2.6940e-02, 3.6390e-02, 4.7170e-02, 5.9240e-02, 7.2560e-02,
       8.7090e-02, 1.0280e-01, 1.1965e-01, 1.3760e-01, 1.5660e-01,
       1.7661e-01, 1.9760e-01, 2.1951e-01, 2.4231e-01, 2.6594e-01,
       2.9035e-01, 3.1551e-01, 3.4135e-01, 3.6782e-01, 3.9488e

In [58]:
y = array[:,1]

In [59]:
y

array([ 0.00126,  0.00274,  0.00537,  0.00862,  0.01231,  0.01629,
        0.02045,  0.02474,  0.02907,  0.0334 ,  0.03769,  0.0419 ,
        0.046  ,  0.04995,  0.05374,  0.05734,  0.06073,  0.06388,
        0.06679,  0.06944,  0.0718 ,  0.07387,  0.07564,  0.07709,
        0.07821,  0.07893,  0.07922,  0.07907,  0.07849,  0.0775 ,
        0.07609,  0.07429,  0.07211,  0.06957,  0.0667 ,  0.0635 ,
        0.06001,  0.05625,  0.05226,  0.04805,  0.04366,  0.03911,
        0.03443,  0.02965,  0.0248 ,  0.01988,  0.01493,  0.00996,
        0.00498,  0.     , -0.00482, -0.00935, -0.01357, -0.01749,
       -0.02112, -0.02445, -0.02749, -0.03023, -0.03269, -0.03485,
       -0.03674, -0.03833, -0.03966, -0.04071, -0.04151, -0.04205,
       -0.04236, -0.04244, -0.04231, -0.04199, -0.0415 , -0.04086,
       -0.04008, -0.03919, -0.03822, -0.03715, -0.03592, -0.03457,
       -0.03309, -0.03151, -0.02985, -0.02813, -0.02635, -0.02453,
       -0.02268, -0.02082, -0.01896, -0.01711, -0.01527, -0.01

In [60]:
from xfoil.model import Airfoil

In [61]:
naca2412 = Airfoil(x=x, y=y)

In [84]:
xf.airfoil = naca2412

In [76]:
xf.Re = 1e5

In [77]:
xf.max_iter = 40

In [70]:
a, cl, cd, cm, cp = xf.aseq(0,10,0.5)

In [71]:
xf.aseq(0,15,0.5)

(array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
         5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
        11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5]),
 array([0.23717791, 0.29031599, 0.34184209, 0.39279974, 0.45046204,
        0.51905435, 0.59209079, 0.66732341, 0.71505284, 0.762869  ,
        0.80961847, 0.85597485, 0.90223002, 0.94779193, 0.99421293,
        1.04080856, 1.0875361 , 1.13328207, 1.17948127, 1.22409439,
        1.26701438, 1.30676329, 1.34722626, 1.37915337, 1.39519572,
        1.42746544, 1.45588815, 1.4800477 , 1.50039351, 1.51481378]),
 array([0.00561373, 0.00550732, 0.0054488 , 0.00552677, 0.00573467,
        0.00600293, 0.00629108, 0.00661807, 0.00691406, 0.00725218,
        0.0077359 , 0.00831522, 0.00901583, 0.00987155, 0.01069411,
        0.01151019, 0.012299  , 0.01314381, 0.01390265, 0.01474385,
        0.01564459, 0.01670419, 0.01758167, 0.01874075, 0.02079311,
        0.02192885, 0.0233745 , 0.02520698, 

In [81]:
cl, cd, cm, cp = xf.a(10)

In [83]:
xf.a(10)[0]

1.153372049331665

In [82]:
cl

1.153372049331665